"""add indexes and defaults

Revision ID: 95069955ed16
Revises: 514d7bbe3384
Create Date: 2026-09-21 21:48:58.938324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95069955ed16'
down_revision: Union[str, None] = '514d7bbe3384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_node_parent_id'), 'node', ['parent_id'], unique=False)
    op.create_index(op.f('ix_node_story_id'), 'node', ['story_id'], unique=False)
    op.create_index(op.f('ix_option_node_id'), 'option', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_option_node_id'), table_name='option')
    op.drop_index(op.f('ix_node_story_id'), table_name='node')
    op.drop_index(op.f('ix_node_parent_id'), table_name='node')
    # ### end Alembic commands ###
